### ISSUE TITLE
The ipaddress will always be null when trying to connect to azure vm

### ISSUE THREAD

**Issue by ader1990** [FawcettJohnW/Framework-Scripts#3]
There is a name mismatch between the Public IP address resource where it is created and where it is used:

Here is used with the name: $vmname
https://github.com/FawcettJohnW/Framework-Scripts/blob/master/run_borg_azure.ps1#L298

vs

here is created with the name $vmname-pip
https://github.com/FawcettJohnW/Framework-Scripts/blob/master/launch_single_azure_vm.ps1#L38

**Comment by FawcettJohnW** [comment]
Code was changed appropriately, a few times :)
